// Internal support/ops inbox for notices generated by product events
// (contact form submissions, new startup submissions, etc).
export const INTERNAL_NOTICE_EMAILS = ["hi@eaglegrowthpartners.com", "saqlain@heva.ai", "fazal@heva.ai"];
